site_name: Intelligent Document Processing
site_description: Anything to process documents Intelligently.
site_author: Christopher Helm
site_url: https://idp-software.com

# Repository - using custom "Find Vendor" button instead of GitHub link
repo_name: atraining/idp-software.com
repo_url: https://github.com/atraining/idp-software.com
edit_uri: edit/main/docs/

# Copyright
copyright: Homepage by <a href="https://www.linkedin.com/in/christopher-helm-public/" target="_blank">Christopher Helm</a>

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  font: false
  features:
    - navigation.tabs
    # - navigation.sections # otherwise the left sidebar will not toggle
    - navigation.collapse
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: favicon.ico

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html

# Validation settings https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

plugins:
  - search
  - rss
  - awesome-pages
  - open-in-new-tab
  - minify:
      minify_html: true
  - ultralytics:
      verbose: False
      # default_image: "https://www.ultralytics.com/images/social.png" # Example default image
      # default_author: "git@ultralytics.com" # Example default author
      add_desc: True
      add_image: True
      add_keywords: False
      add_share_buttons: False
      add_authors: True # Show git authors in footer
      add_json_ld: False # Disabled - using custom hook instead
      add_css: True

# Hooks
hooks:
  - hooks/copy_files_hook.py
  - hooks/jsonld_hook.py

# Custom CSS
extra_css:
  - assets/css/extra.css

# Custom JavaScript
extra_javascript:
  - assets/js/extra.js